# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-16 07:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='x',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='y',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
