# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-06-09 07:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20191216_1645'),
        ('account', '0002_auto_20210409_0831'),
    ]

    operations = [
    ]
