# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-12-16 00:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fsty_cad_design_data',
            name='Linkage_code',
            field=models.CharField(default=None, max_length=5000, null=True),
        ),
    ]
