# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-03-05 08:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_beam_receivingdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='yarn',
            name='Receivingdate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
