# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-03-06 02:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0003_yarn_receivingdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beam',
            name='Receivingdate',
            field=models.CharField(default=datetime.datetime(2020, 3, 6, 11, 18, 55, 284716), max_length=100),
        ),
    ]
