# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-03-06 02:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0004_auto_20200306_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beam',
            name='Receivingdate',
            field=models.CharField(default=datetime.datetime(2020, 3, 6, 11, 30, 37, 679438), max_length=16),
        ),
    ]
