# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-03-13 03:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0015_auto_20200310_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beam',
            name='Receivingdate',
            field=models.CharField(default='2020-03-13 12:17', max_length=30),
        ),
        migrations.AlterField(
            model_name='yarn',
            name='Receivingdate',
            field=models.CharField(default='2020-03-13 12:17', max_length=30),
        ),
    ]
