# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-03-20 04:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0020_auto_20200317_1137'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rollname', models.CharField(max_length=25, null=True)),
                ('rollfabricname', models.CharField(max_length=30, null=True)),
                ('rollfabricdate', models.DateField(default=None, null=True)),
                ('rolloutdate', models.DateField(default=None, null=True)),
                ('receivingdate', models.DateField(default=datetime.datetime(2020, 3, 20, 13, 47, 36, 850045))),
                ('rollcount', models.IntegerField()),
                ('rollfabricerror', models.IntegerField()),
                ('rollfabrictrue', models.IntegerField()),
                ('rollfabriclength', models.IntegerField()),
                ('rollfabricweight', models.IntegerField()),
            ],
            options={
                'db_table': 'Fabric_Roll',
            },
        ),
        migrations.AlterField(
            model_name='beam',
            name='Receivingdate',
            field=models.CharField(default='2020-03-20 13:47', max_length=30),
        ),
        migrations.AlterField(
            model_name='yarn',
            name='Receivingdate',
            field=models.CharField(default='2020-03-20 13:47', max_length=30),
        ),
    ]
