# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-03-20 04:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0021_auto_20200320_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beam',
            name='Receivingdate',
            field=models.CharField(default='2020-03-20 13:50', max_length=30),
        ),
        migrations.AlterField(
            model_name='roll',
            name='receivingdate',
            field=models.DateField(default=datetime.datetime(2020, 3, 20, 13, 50, 57, 407973)),
        ),
        migrations.AlterField(
            model_name='yarn',
            name='Receivingdate',
            field=models.CharField(default='2020-03-20 13:50', max_length=30),
        ),
    ]
