# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-03-20 04:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0023_auto_20200320_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roll',
            name='receivingdate',
            field=models.DateField(default=datetime.datetime(2020, 3, 20, 13, 52, 50, 44893)),
        ),
    ]
