# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-03-20 05:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0024_auto_20200320_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beam',
            name='Receivingdate',
            field=models.CharField(default='2020-03-20 14:23', max_length=30),
        ),
        migrations.AlterField(
            model_name='roll',
            name='receivingdate',
            field=models.DateField(default=datetime.datetime(2020, 3, 20, 14, 23, 26, 189740)),
        ),
        migrations.AlterField(
            model_name='yarn',
            name='Receivingdate',
            field=models.CharField(default='2020-03-20 14:23', max_length=30),
        ),
    ]
