# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-04-01 01:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0025_auto_20200320_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='yarn',
            name='weght',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='beam',
            name='Receivingdate',
            field=models.CharField(default='2020-04-01 10:44', max_length=30),
        ),
        migrations.AlterField(
            model_name='roll',
            name='receivingdate',
            field=models.DateField(default=datetime.datetime(2020, 4, 1, 10, 44, 17, 850571)),
        ),
        migrations.AlterField(
            model_name='yarn',
            name='Receivingdate',
            field=models.CharField(default='2020-04-01 10:44', max_length=30),
        ),
    ]
