# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-04-01 02:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0026_auto_20200401_1044'),
    ]

    operations = [
        migrations.RenameField(
            model_name='yarn',
            old_name='weght',
            new_name='weight',
        ),
        migrations.AlterField(
            model_name='beam',
            name='Receivingdate',
            field=models.CharField(default='2020-04-01 11:05', max_length=30),
        ),
        migrations.AlterField(
            model_name='roll',
            name='receivingdate',
            field=models.DateField(default=datetime.datetime(2020, 4, 1, 11, 5, 23, 435264)),
        ),
        migrations.AlterField(
            model_name='yarn',
            name='Receivingdate',
            field=models.CharField(default='2020-04-01 11:05', max_length=30),
        ),
    ]
