# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-04-08 06:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0027_auto_20200401_1105'),
        ('materials', '0006_auto_20201201_1704'),
    ]

    operations = [
    ]
