# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-05-14 05:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0028_merge_20210408_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beam',
            name='Receivingdate',
            field=models.CharField(default='2021-05-14 14:12', max_length=30),
        ),
        migrations.AlterField(
            model_name='roll',
            name='receivingdate',
            field=models.DateTimeField(blank=True, default='2021-05-14 14:12', null=True),
        ),
        migrations.AlterField(
            model_name='roll',
            name='rollfabricdate',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='roll',
            name='rolloutdate',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='yarn',
            name='Receivingdate',
            field=models.CharField(default='2021-05-14 14:12', max_length=30),
        ),
    ]
