# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-16 07:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='knit_machine',
            old_name='trs_code',
            new_name='tns_code',
        ),
        migrations.RenameField(
            model_name='warp_machine',
            old_name='tws_code',
            new_name='tns_code',
        ),
    ]
