# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-04-08 06:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_style_order_factory_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Style_orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style_key', models.CharField(max_length=500)),
                ('factory_code', models.CharField(max_length=100)),
                ('factory_name', models.CharField(max_length=100, null=True)),
                ('style_ver', models.CharField(max_length=100)),
                ('design_ck', models.BooleanField(default=False)),
                ('fabric_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Style_fabric')),
            ],
        ),
    ]
