# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-04-08 06:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_style_orders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='style_order',
            name='fabric_info',
        ),
        migrations.DeleteModel(
            name='Style_order',
        ),
    ]
