# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-04-08 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20210408_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='style_fabric',
            name='dyeCompanyCode',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='style_fabric',
            name='knitCompanyCode',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
