# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-04-08 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_auto_20210408_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='style_fabric',
            name='FabricCsm',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='style_fabric',
            name='FabricLoss',
            field=models.FloatField(null=True),
        ),
    ]
