# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-04-08 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_auto_20210408_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_designdata',
            name='code',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
