# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-05-14 05:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_auto_20210408_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_designdata',
            name='order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_design', to='order.Order'),
        ),
    ]
