# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-06-09 07:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_auto_20210514_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='value',
            field=models.BooleanField(default=False),
        ),
    ]
